# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package  # name of the workflow

on:
  push:
    branches: [master] # whenever we push our code on master branch this workflow needs to be triggered

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3 # fetches source code of our repo in the environment
      - name: Use nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v3 # setup nodejs on the environment
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: pm2 restart backendserver
      
